all:
	gcc -o q01 q01.c -pthread
	gcc -o q02 q02.c -pthread
	gcc -o q03 q03.c -pthread
	gcc -o q04 q04.c -pthread
	gcc -o q05 q05.c -pthread

pdf: 
	pdflatex -shell-escape asgn1.tex
	rm -Rf asgn1.log asgn1.aux
