all:
	gcc -o q01 q01.c -lpthread -lm
	gcc -o q01_100 q01_100.c -lpthread -lm
	gcc -o q02 bbuf.c -lpthread -lm
	gcc -o q02_100 bbuf_100.c -lpthread -lm
	gcc -o q03 q03.c -lpthread -lm
	gcc -o q03_100 q03_100.c -lpthread -lm
	gcc -o ctime ctime.c 

